// Generated by tools/kit_builder.py from spec/kits/lofi/kit.json. Do not edit: change the
// json and rerun `python3 tools/kit_builder.py spec/kits/lofi/kit.json firmware/src/engine/kits/lofi.h`.
#pragma once

#include "engine/kit.h"

namespace engine::kits {

inline constexpr Kit kLofi{
    "lofi",
    {
        {"kick", Voice::sample, "kick.wav", 0, 0.0f, 1.0f, 0, 1, 4,
         {{1, {{1, 0}}}, {2, {{1, 0}, {1, 0}}}, {3, {{1, 0}, {1, 0}, {1, 0}}}, {4, {{1, 0}, {1, 0}, {1, 0}, {1, 0}}}}},
        {"snare", Voice::sample, "snare.wav", 0, 0.0f, 1.0f, 0, 1, 2,
         {{2, {{0, 0}, {1, 0}}}, {4, {{0, 0}, {1, 0}, {0, 0}, {1, 0}}}}},
        {"hat", Voice::sample, "hat.wav", 0, 0.0f, 1.0f, 0, 1, 2,
         {{2, {{1, 0}, {1, 0}}}, {4, {{1, 0}, {1, 0}, {1, 0}, {1, 0}}}}},
        {"clap", Voice::sample, "clap.wav", 0, 0.0f, 1.0f, 0, 1, 2,
         {{2, {{0, 0}, {1, 0}}}, {4, {{0, 0}, {1, 0}, {0, 0}, {1, 0}}}}},
        {"bass", Voice::synth, "sub-saw", 0, 0.0f, 0.0f, 2, 0, 1,
         {{1, {{1, 0}}}}},
        {"chord", Voice::synth, "warm-poly", 0, 0.0f, 0.0f, 4, 4, 1,
         {{1, {{1, 0}}}}},
        {"pluck", Voice::synth, "keys", 0, 0.0f, 0.0f, 5, 3, 1,
         {{1, {{1, 0}}}}},
        {"rim", Voice::sample, "rim.wav", 0, 0.0f, 1.0f, 0, 1, 1,
         {{1, {{1, 0}}}}},
    },
    {{4, {0, 5, 2, 6}}, {4, {0, 4, 5, 3}}, {4, {0, 3, 6, 3}}, {4, {0, 4, 1, 2}}, {4, {0, 4, 1, 3}}},
    {8, {0, 2, 4, 7, 9, 7, 4, 2}},
    3,
    {"PB2:lofi:100:10:2:0:15:cm:e10000-e1.0.0-e10000-e1-e100-e10123-e1-e1",
     "PB2:lofi:100:10:2:0:15:cm:e10-e1.0-e100000-e1.0-e10-e101-e10123-e1",
     "PB2:lofi:100:10:2:0:15:cm:e1008-e1.0.0-e1000000-b1.0.0-e10000-e10123-e101-e10."},
    15,
    10,
    2,
    {true, 5, 120},
};

}  // namespace engine::kits
